// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogSUXh3jwF5Iat0thuvFVkOE8MQ7leR8',
    appId: '1:719722301920:web:efd5d2bd15a1b1b7b7c385',
    messagingSenderId: '719722301920',
    projectId: 'fcmtest-41357',
    authDomain: 'fcmtest-41357.firebaseapp.com',
    storageBucket: 'fcmtest-41357.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vP9u-BeXQUiILtKXuZzbHisd-XFdHFA',
    appId: '1:719722301920:android:fc066c6b1d1ad44cb7c385',
    messagingSenderId: '719722301920',
    projectId: 'fcmtest-41357',
    storageBucket: 'fcmtest-41357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4U6I3j6XRVvmqhvAxxn0YRk-urSwkyM',
    appId: '1:719722301920:ios:39f1b8758473a25db7c385',
    messagingSenderId: '719722301920',
    projectId: 'fcmtest-41357',
    storageBucket: 'fcmtest-41357.appspot.com',
    iosClientId: '719722301920-mmkujrvai3b1dtch4v7jv244qqqenban.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmtest',
  );
}
